{%- macro interfaces(name, mac) -%}
      - name: {{ name }}
        type: ethernet
        state: up
        mac-address: {{ mac }}
{%- endmacro %}

{% macro bond(name, mode) -%}
      - name: {{ name }}
        type: bond
        state: up
        link-aggregation:
          mode: {{ mode }}
          port:
          - eth0
          - eth1
{%- endmacro %}

{% macro ip(mode, ip, prefix) -%}
{% if mode == "DHCP" -%}
          {% if ip is ansible.utils.ipv6 %}autoconf: true
          {% endif %}auto-dns: false
          enabled: true
          dhcp: true
          auto-gateway: true
          auto-routes: true
{%- else -%}
          enabled: true
          address:
            - ip: {{ ip }}
              prefix-length: {{ prefix }}
          dhcp: false
{%- endif -%}
{%- endmacro %}

{% macro dns(ext_ip) -%}
    dns-resolver:
      config:
        server:
          - {{ ext_ip }}
{%- endmacro %}

{% macro route(interface, dest, ext_ip) -%}
    routes:
      config:
        - destination: {{ dest }} 
          next-hop-address: {{ ext_ip }}
          next-hop-interface: {{ interface }}
          table-id: 254
{%- endmacro %}

{% macro dns_dualstack(ext_ip, dualstack_ext_ip) -%}
    dns-resolver:
      config:
        server:
          - {{ ext_ip }}
          - {{ dualstack_ext_ip }}
{%- endmacro %}

{% macro route_dualstack(interface, ext_ip, dualstack_ext_ip) -%}
    routes:
      config:
        - destination: 0.0.0.0/0 
          next-hop-address: {{ ext_ip }}
          next-hop-interface: {{ interface }}
          table-id: 254
        - destination: ::/0 
          next-hop-address: {{ dualstack_ext_ip }}
          next-hop-interface: {{ interface }}
          table-id: 254
{%- endmacro %}
